### ISSUE TITLE
[BUG] Could not perform command

### ISSUE THREAD

**Issue by grantal2343** [OthersideAI/self-operating-computer#201] opened 2024-07-05 11:53 UTC
Good Morning,

When I installed the self operating computer and gave a basic command it did not work and gave an error message. Below is a printscreen of what happened with the error. What should I do? The error said:

[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
[Self-Operating Computer][Error] -> cannot access local variable 'content' where it is not associated with a value

Attached is a screenshot. Thank you! 

![image](https://github.com/OthersideAI/self-operating-computer/assets/97428779/e6a7204b-6f10-403f-a840-14ca29741023)

![image](https://github.com/OthersideAI/self-operating-computer/assets/97428779/39e8f393-e3b1-4c4e-913a-3173b8400508)

**Comment by joshbickett** [comment] 2024-07-09 18:20
Hello, the old model has been replaced with `gpt-4o` and should be working now. I merged in the branch below. Please update to `Version: 1.4.6` and let me know if the issue is not resolved for you. 

```
https://github.com/OthersideAI/self-operating-computer/tree/gpt-4o
```

**Closed by joshbickett** 2024-07-09 18:20 UTC
Labels: bug
