### ISSUE TITLE
Object detection 

### ISSUE THREAD

**Issue by admineral** [OthersideAI/self-operating-computer#12] opened 2023-11-29 14:21 UTC
Maybe a yolo object detection model trained on basic things to get coordinates? Or something like sam?

i mean as soon as there is a small model, gpt4 can check the dataset and add more correct examples to the trainigset

**Comment by KBB99** [comment] 2023-12-11 19:38
Sounds awesome. We could look at using this: https://github.com/luca-medeiros/lang-segment-anything

**Comment by michaelhhogue** [comment] 2023-12-11 22:14
@admineral Yeah sorry, not sure why I closed this. I must've been tired. This is a good idea! 

@KBB99 Looking at this now and it looks really interesting. I hadn't considered a segmentation model before

**Comment by KBB99** [comment] 2023-12-12 05:06
Have a long way to go, but was able to [get it integrated](https://github.com/KBB99/self-operating-computer/tree/main). I need to make sure the calculations I'm performing are correct as well as modify the ratio conversion. Right now it's incredibly slow as I'm running it locally, but I'll try to host an endpoint backed by a GPU to speed it up. Later I'd like to explore a RL mechanism similar to what @admineral mentioned to improve pixel coordinates estimation.

If anyone wants to continue working on it feel free to clone the fork! Just a note you need to use Python3.9 and the Lang model takes over 4GB of space.

**Comment by Daisuke134** [comment] 2023-12-25 01:23
@KBB99 Thank you! I was trying to implement SoM, but the accuracy of labels for screenshots were quite low, so I was trying to look into other ways of solving the problem. 

I was trying to implement som using "som-mode", and implementing prompt into VISION PROMPT. 

I will check and try your code. Thank you so much!

**Comment by Daisuke134** [comment] 2023-12-25 08:48
Looks great! I was looking into your code, and here are some things I thought. 

・I think you are using summary_prompt to make gpt4 respond with the label for the next action, but probably this is not related to SUMMARY_PROMPT, right? I found it a bit confusing, so maybe changing names is better. 

・Also, how about combining summary_prompt and VISION PROMPT? We give gpt4v screenshot with Sam + ask it to give the specific label too(CLICK {{ “label”: “C", “description”... ), then we do not need to request GPT4 twice, reducing the operation time. 

・I have thought about making a new mode like som_mode. Here is my code.

`
def main_entry():
    # Add SoM to image
    parser.add_argument(
        "-som",
        help="Activate SOM Mode",
        action="store_true",
        required=False,
)
    try:
         main(
            args.model,
            accurate_mode=args.accurate,
            terminal_prompt=args.prompt,
            som_mode=args.som,
            voice_mode=args.voice,
             )
`

**Comment by joshbickett** [comment] 2023-12-25 14:25
> @joshbickett how do you suggest building this into the project? operate --click_mode=lang-som ?

@KBB99 excited to look closer. Let me checkout the code and provide some input in the next few days

**Comment by joshbickett** [comment] 2023-12-25 16:00
@KBB99 I did `git checkout` on your fork. I am encountering the following issue. 

```
TypeError: mouse_click() missing 2 required positional arguments: 'client' and 'messages'
```
It looks like `mouse_click` was expecting additional arguments
```
if action_type == "SEARCH":
            function_response = search(action_detail)
        elif action_type == "TYPE":
            function_response = keyboard_type(action_detail)
        elif action_type == "CLICK":
            function_response = mouse_click(action_detail)
        else:
...
def mouse_click(click_detail, client, messages):
```

After adjusting that in the code so that `mouse_click` doesn't encounter that error I got the following result, but didn't see the mouse move or click .
```
[Self-Operating Computer] [Act] CLICK {'visual_description': "First link in the list of articles, titled 'Non-interactive SSH password authentication'", 'reason': 'To open the top article as requested'}
```
I am interested in this `lang-som` approach but it looks like it may need more work, let me know if there's something I was doing wrong. I'd love to try out a working version.

**Comment by KBB99** [comment] 2023-12-26 00:35
Hey @joshbickett . Yes I made some changes to clean up the code before pushing and must have broke something accidentally, will take a look and update any glitches. Thanks for checking it out!

**Comment by Daisuke134** [comment] 2023-12-26 01:28
@KBB99 
Hi. I was trying to test out your code, but had some issues installing lang_sam. I am using Python 3.12 and tried to install torch and torchvision but was not able to. 

We need to 
pip install torch torchvision
pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git
to run the project, right?

**Comment by joshbickett** [comment] 2023-12-26 01:58
@Daisuke134 i was able to install with Python 3.9 and the commands you mentioned.

**Comment by KBB99** [comment] 2023-12-26 04:24
@joshbickett I updated the incorrect arguments you mentioned so that is fixed. It is moving and clicking for me so I suspect that for the generated visual description, `First link in the list of articles, titled 'Non-interactive SSH password authentication` lang-sam did not identify the object and hence couldn't click on anything. For me it sometimes segments and masks the objects correctly, but other times not. I need to experiment more and improve the prompts as well as the marks.

@Daisuke134 the commands you mentioned are correct assuming you start with python 3.9 venv (to do so set up the venv by running `python3.9 -m venv venv`). Also, don't forget to pull the latest changes that fix the arguments bug Josh mentioned.

I will do some more tests, improvements, and then make a pull request tomorrow integrating the suggestions @Daisuke134 mentioned.

**Comment by Daisuke134** [comment] 2023-12-26 07:10
@joshbickett thank you! I installed 3.9.18 + made new environment called "new-env" + pip install torch torchvision, but when I did "pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git", the error says "ModuleNotFoundError: No module named 'torch'". Do you know what the problem is?

**Comment by Daisuke134** [comment] 2023-12-26 09:19
@joshbickett @KBB99 Thank you. I could run the code using 3.9.18. However, when I did operate and "Go to youtube.com and play some holiday music", there is an error saying 

Error parsing JSON: 'ascii' codec can't encode character '\u2018' in position 7: ordinal not in range(128)
[Self-Operating Computer][Error] something went wrong :(
[Self-Operating Computer][Error] AI response
Failed take action after looking at the screenshot

Any idea how to solve the problem?

**Comment by joshbickett** [comment] 2023-12-26 14:53
> Any idea how to solve the problem?

sounds like you were able to resolve this issue, but wanted to mention that I had to run `pip install torchvision ` separate before `lang-segment-anything`

**Comment by KBB99** [comment] 2023-12-26 22:30
So I've managed to fix the clicking errors as well as add a configuration that saves the screenshots, masked screenshots, prompt, and predicted coordinates. I'll run more tests and keep expanding the dataset to test the segmentation model individually and then make further changes. Sometimes lang-sam works very well and segments the targeted object perfectly making clicks extremely accurate, other times not.

@joshbickett are you aware of any dataset of screenshots with target object and coordinates we could use to evaluate different approaches?

**Comment by Daisuke134** [comment] 2023-12-26 22:56
> run `pip install torchvision ` separate before `lang-segment-anything`

**Comment by KBB99** [comment] 2023-12-27 03:26
@Daisuke134 I added a section to the README.md try following the one with Cond version.

**Comment by joshbickett** [comment] 2024-01-07 18:35
@admineral @KBB99 Set-of-Mark prompting is [now available](https://x.com/josh_bickett/status/1744060046361968786?s=20). You can swap in any `best.pt` from a YOLOv8 model and see how it performs. I'd love if the community iterated on what I built. My `best.pt` could be improved, but the structure is now in to improve upon.

**Comment by KBB99** [comment] 2024-01-10 04:12
@joshbickett I've played around with the SOM you implemented, but for some reason GPT-V seems to pick the wrong marks and still doesn't click on the correct object. I think some additional context, like the text could help GPT-V pick the correct object better. I've been experimenting with Amazon Textract Layout and it seems pretty solid, capturing text and the layout. Take a look at the screenshot. I'll test it with self-operating-computer and let you know how it goes.
<img width="1440" alt="Screenshot 2024-01-09 at 11 05 16 PM" src="https://github.com/OthersideAI/self-operating-computer/assets/19329998/32ca8091-c753-4fe2-ab63-74b44c311225">

**Comment by joshbickett** [comment] 2024-01-10 17:06
@KBB99 sounds good. If it improves performance it'd be great to get a PR

**Comment by admineral** [comment] 2024-01-29 14:58
https://github.com/ardamavi/Game-Bot maybe? add workflows , marketplace, share data and train a big base model with a lot of workflows by watching the user fr a few days

**Comment by joshbickett** [comment] 2024-02-09 05:35
@KBB99 I'll close this PR for now that we're using the OCR method as default. If anyone comes up with an improved YOLO model or SOM technique feel free to open a new ticket or a PR!

**Closed by joshbickett** 2024-02-09 05:35 UTC

**Comment by admineral** [comment] 2024-02-15 15:30
Please check out https://blog.roboflow.com/what-is-yolo-world/
