### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by michsiu** [OthersideAI/self-operating-computer#137] opened 2024-01-17 04:14 UTC
I encountered the issue `Error parsing JSON: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses;`

And now I have resolved the issue with the help of `https://github.com/google/generative-ai-python/issues/117`

I have tested it on my computer and it works

As it says that it needs to add `transport='rest'` on API config `genai.config`

But I did not find the `genai.config` on the program

So what should I do if I want to config the `transport='rest'`

**Comment by joshbickett** [comment] 2024-01-19 21:59
@michsiu thanks for the ticket. I noticed it may be a duplicate of #138 so I'll close this one. I wanted to mention this should be fixed now. Please try and let me know if it is still an issue for you in #138. Thanks

**Closed by joshbickett** 2024-01-19 21:59 UTC
Labels: bug
