### ISSUE TITLE
Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

### ISSUE THREAD

**Issue by koenjah** [OthersideAI/self-operating-computer#198] opened 2024-06-21 21:37 UTC
Describe the bug
The "Self-Operating Computer" software fails to open Chrome and encounters an error related to a deprecated OpenAI model. Additionally, there's an internal error about a variable named "content" that's not accessible.

Steps to Reproduce
Run the "Self-Operating Computer" software.
Enter the command "open chrome".
The software attempts to open Chrome but fails.
An error message appears indicating that the model "gpt-4-vision-preview" has been deprecated.
An additional error message appears stating "cannot access local variable 'content' where it is not associated with a value".
Expected Behavior
The software should successfully open the Chrome browser upon receiving the "open chrome" command.

Actual Behavior
The software fails to open Chrome, displaying two error messages: one about the deprecated OpenAI model and another about an internal variable access issue.

Environment
OS: macOS (likely other operating systems could be affected as well)
Model Used: gpt-4-vision-preview (deprecated)

**Comment by 921kiyo** [comment] 2024-06-25 15:58
I am getting also getting "The model `gpt-4-vision-preview` has been deprecated" error.

**Comment by Latryna** [comment] 2024-07-02 20:04
It looks like the model `gpt-4-vision-preview` you are trying to use has been deprecated and is no longer available. The 404 error indicates that the model was not found.

### How to resolve the issue with the deprecated model:

1. **Check available models on OpenAI**:
   Visit the [OpenAI API Models](https://platform.openai.com/docs/models) page and check which models are available. Make sure you are using a model that is currently supported.

2. **Update your application configuration**:
   If your application's configuration file or code refers to the `gpt-4-vision-preview` model, change this reference to a current model. For example:

   ```python
   # Replace 'gpt-4-vision-preview' with a current model, e.g., 'gpt-4-turbo' or 'gpt-4'
   model_name = "gpt-4-turbo"  # example
   ```

3. **Update the application code**:
   If your application code directly refers to the model, make sure to change the reference from the deprecated model to the new model everywhere. Here's an example of what this might look like:

   ```python
   import openai

   openai.api_key = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
   
   response = openai.Completion.create(
       engine="gpt-4-turbo",  # Update the model name here
       prompt="Hello, world!",
       max_tokens=50
   )
   ```

4. **Test the changes**:
   Restart your application to ensure the changes have been applied correctly and the application works as expected.

### Example of updating the configuration file:

If your configuration file contains references to the model, update it accordingly:

```python
class Config:
    def __init__(self):
        load_dotenv()
        self.verbose = False
        self.openai_api_key = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        self.google_api_key = None
        self.anthropic_api_key = None
        self.model_name = "gpt-4-turbo"  # Update the model name here
```

### Example of updating in application code:

If your application code has direct references to the model:

```python
import openai

openai.api_key = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

def generate_response(prompt):
    response = openai.Completion.create(
        engine="gpt-4-turbo",  # Update the model name here
        prompt=prompt,
        max_tokens=50
    )
    return response.choices[0].text

# Example call to the function
print(generate_response("Hello, world!"))
```

Update all instances where you refer to `gpt-4-vision-preview` to use the new model, such as `gpt-4-turbo`.

After making these changes, restart your application and check if the issue is resolved. If you still encounter difficulties, let me know and I will assist further!

**Comment by EdenIsHereToStay** [comment] 2024-07-08 15:34
Hello,

I'm encountering an issue with the Self-Operating Computer. After attempting to use the tool, I receive the following error message:

```
[Self-Operating Computer | gpt-4-with-ocr]
Hello, I can help you with anything. What would you like done?
[User]
What do you see?
[Self-Operating Computer][gpt-4-with-ocr] That did not work. Trying another method
[Self-Operating Computer][Operate] That did not work. Trying again  Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
[Self-Operating Computer][Error] -> local variable 'content' referenced before assignment
```

Steps I have taken so far:

API Key:

Confirmed I have an active API key and sufficient credits.
Met the $5 credit requirement mentioned in user discussions.
Updating Software:

Updated Python to the latest version.
Ran self-operating-computer update to ensure I have the latest version of the tool.
Configuration:

Checked my configuration files for any discrepancies.
Despite these steps, the issue persists across multiple installations on different machines. The error message indicates that the gpt-4-vision-preview model has been deprecated. I have followed the official documentation, but I am still unable to resolve this issue.

Any guidance on resolving this would be greatly appreciated.

Thank you!

**Comment by joshbickett** [comment] 2024-07-09 18:20
Hello, the old model has been replaced with `gpt-4o` and should be working now. I merged in the branch below. Please update to `Version: 1.4.6` and let me know if the issue is not resolved for you. 

```
https://github.com/OthersideAI/self-operating-computer/tree/gpt-4o
```

**Closed** 2024-07-09 18:21 UTC
Labels: bug

**Comment by EdenIsHereToStay** [comment] 2024-07-09 19:25
I'll try it out and lyk. Thanks!
